package io.safari94.trimblems.soap.tracking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrackingService", targetNamespace = "http://fleetworks.acunia.com/fleet/service", wsdlLocation = "https://soap.box.trimbletl.com/fleet-service/Tracking?wsdl")
public class TrackingService
    extends Service
{

    private final static URL TRACKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACKINGSERVICE_EXCEPTION;
    private final static QName TRACKINGSERVICE_QNAME = new QName("http://fleetworks.acunia.com/fleet/service", "TrackingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://soap.box.trimbletl.com/fleet-service/Tracking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRACKINGSERVICE_WSDL_LOCATION = url;
        TRACKINGSERVICE_EXCEPTION = e;
    }

    public TrackingService() {
        super(__getWsdlLocation(), TRACKINGSERVICE_QNAME);
    }



    public TrackingService(URL wsdlLocation) {
        super(wsdlLocation, TRACKINGSERVICE_QNAME);
    }




    /**
     * 
     * @return
     *     returns Tracking
     */
    @WebEndpoint(name = "TrackingPort")
    public Tracking getTrackingPort() {
        return super.getPort(new QName("http://fleetworks.acunia.com/fleet/service", "TrackingPort"), Tracking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tracking
     */
    @WebEndpoint(name = "TrackingPort")
    public Tracking getTrackingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fleetworks.acunia.com/fleet/service", "TrackingPort"), Tracking.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACKINGSERVICE_EXCEPTION!= null) {
            throw TRACKINGSERVICE_EXCEPTION;
        }
        return TRACKINGSERVICE_WSDL_LOCATION;
    }

}
