
package io.safari94.trimblems.soap.planning;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlanningService", targetNamespace = "http://fleetworks.acunia.com/fleet/service", wsdlLocation = "https://soap.box.trimbletl.com/fleet-service/Planning?wsdl")
public class PlanningService
    extends Service
{

    private final static URL PLANNINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLANNINGSERVICE_EXCEPTION;
    private final static QName PLANNINGSERVICE_QNAME = new QName("http://fleetworks.acunia.com/fleet/service", "PlanningService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://soap.box.trimbletl.com/fleet-service/Planning?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLANNINGSERVICE_WSDL_LOCATION = url;
        PLANNINGSERVICE_EXCEPTION = e;
    }

    public PlanningService() {
        super(__getWsdlLocation(), PLANNINGSERVICE_QNAME);
    }

    public PlanningService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLANNINGSERVICE_QNAME, features);
    }

    public PlanningService(URL wsdlLocation) {
        super(wsdlLocation, PLANNINGSERVICE_QNAME);
    }

    public PlanningService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLANNINGSERVICE_QNAME, features);
    }

    public PlanningService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanningService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Planning
     */
    @WebEndpoint(name = "PlanningPort")
    public Planning getPlanningPort() {
        return super.getPort(new QName("http://fleetworks.acunia.com/fleet/service", "PlanningPort"), Planning.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Planning
     */
    @WebEndpoint(name = "PlanningPort")
    public Planning getPlanningPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fleetworks.acunia.com/fleet/service", "PlanningPort"), Planning.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLANNINGSERVICE_EXCEPTION!= null) {
            throw PLANNINGSERVICE_EXCEPTION;
        }
        return PLANNINGSERVICE_WSDL_LOCATION;
    }

}
