
package io.safari94.trimblems.soap.documents;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "OperationFailedException", targetNamespace = "http://fleetworks.acunia.com/fleet/fault")
public class OperationFailedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OperationFailedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OperationFailedException_Exception(String message, OperationFailedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public OperationFailedException_Exception(String message, OperationFailedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: documents.OperationFailedException
     */
    public OperationFailedException getFaultInfo() {
        return faultInfo;
    }

}
